#ifndef __UI_CONSTANTS_H_
#define __UI_CONSTANTS_H_

#define A_QUEUES_MAX_PEOPLE 120

#define QUEUE_A1_X_VALUE -1200
#define QUEUE_A1_Y_VALUE 50
#define QUEUE_A1_WIDTH 800
#define QUEUE_A1_HEIGHT 430

#define QUEUE_A2_X_VALUE -1200
#define QUEUE_A2_Y_VALUE -480
#define QUEUE_A2_WIDTH 800
#define QUEUE_A2_HEIGHT 430

#define PADDING_BETWEEN_PEOPLE 35

#define RIGHT_DIRECTION 1
#define LEFT_DIRECTION -1

#endif
