#ifndef __UI_CONSTANTS_H_
#define __UI_CONSTANTS_H_

#define A_QUEUES_MAX_PEOPLE 120

#define QUEUE_A1_X_VALUE -1200
#define QUEUE_A1_Y_VALUE 50
#define QUEUE_A1_WIDTH 720
#define QUEUE_A1_HEIGHT 430

#define QUEUE_A2_X_VALUE -1200
#define QUEUE_A2_Y_VALUE -480
#define QUEUE_A2_WIDTH 720
#define QUEUE_A2_HEIGHT 430

#define ROLLING_GATES_X (QUEUE_A1_X_VALUE + QUEUE_A1_WIDTH + 50)
#define ROLLING_GATES_Y 200 // ROLLING_GATES_Y for gate 1 and -ROLLING_GATES_Y for gate 2
#define ROLLING_GATE_SIZE 70.0f
#define ROLLING_GATE_DEGREE_PER_FRAME 7

#define PADDING_BETWEEN_PEOPLE 35
#define STEP_SIZE 10

#define MAX_SPEED_PER_FRAM 0.3
#define FPS 30

#define RIGHT_DIRECTION 1
#define LEFT_DIRECTION -1

#endif
